### ISSUE TITLE
Filter icon does not display in most cases nor does it filter

### ISSUE THREAD

**Issue by sloant** [devmatics/incoming-issues#2]
The filter toggle for the filter container does not display unless one adjusts screensize.
Also it does not seem to actually be changing the display of that container.
This can be seen on all client sites and at https://catalog.devmatics.io/static/preview_sandbox.html#.
![Screenshot from 2022-07-22 15-33-39](https://user-images.githubusercontent.com/104519469/180571597-3431d55b-4314-457d-90a6-66fcbb2adb2e.png)
![Screenshot from 2022-07-22 15-33-18](https://user-images.githubusercontent.com/104519469/180571600-d71e41bb-4e08-4d01-86a1-32a5f6639572.png)

**Comment by flatironic** [comment]
The z-index needed to be higher on the mobile filter button.

**Comment by alexdwhite** [comment]
Tested, confirmed fix works, published to production.  @sloant
