### ISSUE TITLE
ACA Prod Catalog: Failed Sync

### ISSUE THREAD

**Issue by sloant** [devmatics/incoming-issues#3]
The symptom is that product code PEWEB22010 is not showing up in the catalog. I verified that the product does come back in the results of the Products and Attributes queries, respectively.

![download](https://user-images.githubusercontent.com/104519469/185245520-f664eab6-b172-41a6-80bf-a93c64e6fed3.png)

![thumbnail_image008](https://user-images.githubusercontent.com/104519469/185245301-52ab3d03-499d-4cc5-b69c-0b9caecd7905.png)

The Catalog sync for ACA’s production environment is failing though. The sync button is located in their staff site at https://imis.counseling.org/Staff/Shared_Content/ATS/Catalog/Catalog.aspx. I have the button configured to use their APIKEY value = “fgjhDFSjupohCssdHjPm”. When I try to run the sync, I get a failure message as follows:

![download](https://user-images.githubusercontent.com/104519469/185245561-1f8337fb-61e6-4232-9092-7c912cfdefd3.png)

**Comment by alexdwhite** [comment]
Hi @sloant, is it possible the iQA is named wrong?

**Comment by rrichter80** [comment]
Alex,

Just curious. Did you truncate them all or just the credits?

Thanks,
Randy
