### ISSUE TITLE
Search Logging

### ISSUE THREAD

**Issue by sloant** [devmatics/incoming-issues#4]
Are the search terms entered in the Catalog text search box logged or recorded anywhere for analysis?
(ATS note: CW 72706)

**Comment by rrichter80** [comment]
I think someone asked this before. The search button only gets implemented on large data sets. On small ones, it auto filters as you type. The client could sure look at the imis detail page in google analytics to see which pages are the most popular.

Thanks,
Randy

**Comment by sloant** [comment]
Thanks. We had discussed Randy but hadn't put it to Alex yet. Saw it as one of our open ticket questions and wanted to make sure we had a definitive answer if it comes up from client again.
Thanks all!
Tim
